services:
  gdor11-nginx:
    build:
      target: prod
    secrets:
      - fullchain
      - privkey
    networks:
      - gdor11com

  server_test_back:
    networks:
      - gdor11com


secrets:
  fullchain:
    file: /etc/letsencrypt/live/gdor11.com/fullchain.pem
  privkey:
    file: /etc/letsencrypt/live/gdor11.com/privkey.pem

networks:
  gdor11com:
