events {
    worker_connections  1024;
}

http {
    include mime.types;

    server {
        listen 80;
        listen [::]:80;
        http2 on;

        location / {
            alias /srv/static_serve/homepage/;
        }
        location /server_test/ {
            alias /srv/static_serve/server_test/;
        }
        location /server_test/api {
            proxy_pass http://server_test:8080;
        }
    }
}
